/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ArrayGenerate */

#ifndef _Included_ArrayGenerate
#define _Included_ArrayGenerate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ArrayGenerate
 * Method:    arrayGenerator
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ArrayGenerate_arrayGenerator
  (JNIEnv *, jobject, jint);

/*
 * Class:     ArrayGenerate
 * Method:    arrayMinMaxDiff
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_ArrayGenerate_arrayMinMaxDiff
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
