/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ClassifyHonours */

#ifndef _Included_ClassifyHonours
#define _Included_ClassifyHonours
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ClassifyHonours
 * Method:    classifyDiploma
 * Signature: (D)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ClassifyHonours_classifyDiploma
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ClassifyHonours
 * Method:    classifyDegree
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ClassifyHonours_classifyDegree
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
